version: '3'

services:
  www:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
     - "./src:/var/www/html"
    restart: always
    ports:
      - "80:80"
      - "443:443"

  db:
    image: mysql
    volumes:
      - ./db_data:/var/lib/mysql
      - ./init.sql:/data/application/init.sql
    restart: always
    ports:
      - "3306:3306"
    command: --init-file /data/application/init.sql
    environment:
      - MYSQL_DATABASE=php_docker
      - MYSQL_USER=php_docker
      - MYSQL_PASSWORD=php_docker
      - MYSQL_ALLOW_EMPTY_PASSWORD=1

